name: Build Docs

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install docs dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: docs/environment.yml
          environment-name: docs-env
          cache-environment: true
          init-shell: >-
            bash

      - name: Install package in environment
        run:  python -m pip install .
        shell: micromamba-shell {0}

      - name: Check docs can be build + links
        working-directory: docs
        run: |
          sudo apt install -y pandoc
          make html
          python -m pytest --check-links
        shell: micromamba-shell {0}